# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: nami.land
# subtitle: 西交民巷 50 号
# subtitle: Nami's blog
url: "https://nami.land"

# Build settings

# for local dev
# theme: minimal-mistakes-jekyll

# for prod
remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: dirt

repository: "namiwang/namiwang.github.io"

plugins:
- jekyll-include-cache
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
# - jekyll-image-size
# - jekyll-archives
- jekyll-sitemap

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      author: Nami W
      read_time: false
      comments: true
      share: false
      related: true
      show_date: true
      # classes: wide

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# markdown: kramdown
# kramdown:
#   parse_block_html: true

# https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md
# NOTE not supported by github pages
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings
# jekyll-archives:
#   enabled: [tags]
#   # layout: category
#   permalinks:
#     # year: '/:year/'
#     # month: '/:year/:month/'
#     # day: '/:year/:month/:day/'
#     tag: '/tag/:name/'
#     # category: '/category/:name/'
#   layouts:
#     tag: tag

tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: custom
